// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9zadP1qMIxKdIM3c1WUYPZ4UOJPxYZRQ',
    appId: '1:401582756146:web:5888fdad05b4c133a8472b',
    messagingSenderId: '401582756146',
    projectId: 'de-art',
    authDomain: 'de-art.firebaseapp.com',
    storageBucket: 'de-art.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zadP1qMIxKdIM3c1WUYPZ4UOJPxYZRQ',
    appId: '1:401582756146:android:dc98cd597c9e5817a8472b',
    messagingSenderId: '401582756146',
    projectId: 'de-art',
    storageBucket: 'de-art.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa84zX1hi-_YD8PW0fUsC_YVbOx5EkgXM',
    appId: '1:401582756146:ios:f535f886941bcbe5a8472b',
    messagingSenderId: '401582756146',
    projectId: 'de-art',
    storageBucket: 'de-art.appspot.com',
    iosBundleId: 'com.example.deArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa84zX1hi-_YD8PW0fUsC_YVbOx5EkgXM',
    appId: '1:401582756146:ios:53ed5629eacca78ea8472b',
    messagingSenderId: '401582756146',
    projectId: 'de-art',
    storageBucket: 'de-art.appspot.com',
    iosBundleId: 'com.example.deArt.RunnerTests',
  );
}
